### ISSUE TITLE
What is the API_BASE_URL if i am using eth sepolia and confusion between NEXT_PUBLIC_PRIVATE_KEY and ACCOUNT_PRIVATE_KEY

### ISSUE THREAD

**Issue by ghousetazeem** [ahmedsemih/CrowdFunding-dApp#1]
I tried to give localhost:3000 as the API_BASE_URL and also tried to give this as well: https://eth-sepolia.g.alchemy.com/v2
but for both I am getting this error:
src\app\page.jsx (27:20) @ fetch

  25 | 
  26 | const fetchTotalCollected = async () => {
> 27 | const res = await fetch(`${process.env.NEXT_PUBLIC_API_BASE_URL}/total`, {
     |                  ^
  28 |   method: "GET",
  29 |   cache: "no-cache",
  30 | });
  
  Can you just explain me what should I have to use in place of API_BASE_URL and also I am confused in NEXT_PUBLIC_PRIVATE_KEY and ACCOUNT_PRIVATE_KEY, are those different or same?

**Comment by ahmedsemih** [comment]
API_BASE_URL is localhost:3000/api if you are using localhost. And these private key variables must have same value.

**Comment by ghousetazeem** [comment]
![image](https://github.com/ahmedsemih/CrowdFunding-dApp/assets/74200389/d06f3aaa-efb5-4f7b-b446-ee6a525588bc)
this is the error that i am getting and this is my env file: can you just correct this:
![image](https://github.com/ahmedsemih/CrowdFunding-dApp/assets/74200389/a89b86c1-0979-4aed-8cd0-28c41d9abd76)

Its a lot of confusion

**Comment by ghousetazeem** [comment]
and yes i am using the local host

**Comment by ahmedsemih** [comment]
You should write the client environment variables inside the client folder. It looks like you wrote them all inside the smart contract folder. therefore these env variables are undefined.

**Comment by ahmedsemih** [comment]
I wrote which variable belongs to which folder on the readme file.

**Comment by ghousetazeem** [comment]
Thanks for it, but still running into the problem:
![image](https://github.com/ahmedsemih/CrowdFunding-dApp/assets/74200389/ec7e30f8-f94d-4304-b796-633703359546)

Now getting this error:
![image](https://github.com/ahmedsemih/CrowdFunding-dApp/assets/74200389/1b091533-1c72-4c4f-84f6-3eacb746ae73)

please look in to this

**Comment by ahmedsemih** [comment]
Where exactly did you get this issue? I ran the application locally but i didn't see this.

**Comment by ghousetazeem** [comment]
Can you just give me your mobile number, so that we can connect and I can clarify everything. Even I don't know where the issue is. It's clue less not even getting any hint where it's occurring

**Comment by ahmedsemih** [comment]
Then I'm afraid I can't help you. Maybe chatgpt or alternatives can solve the problem.

**Comment by ghousetazeem** [comment]
Ok just tell me how should I configure my smart contract. May be that can solve the problem. The problem I think is in fetching the data from the smart contract.

**Comment by ghousetazeem** [comment]
![image](https://github.com/ahmedsemih/CrowdFunding-dApp/assets/74200389/317de241-5ecb-4a55-a026-ae0a8717fbaf)

and this is what the terminal is showing the error

**Comment by ghousetazeem** [comment]
and also one last thing, when i was trying to install the packages, it should me some error, but i --force did this and downloaded the packages, can that cause any problem?

**Comment by ahmedsemih** [comment]
You already cloned the project and created an alchemy app and deployed your smart contract. Smart contract does not require any other configuration. And no, I don't think --force is causing this problem, I just did the same thing.

**Comment by ghousetazeem** [comment]
Hey some last things to asked.. Where I can see my created campaigns because when I am creating a campaign its not showing up to the website. So I want to know where I can watch them as we can do so in thirdweb

**Comment by ahmedsemih** [comment]
If you are creating the campaign correctly and you are not receiving the message "The campaign could not be created." after the process in the blockchain is completed, the created campaign will be showed in the application.

**Comment by ghousetazeem** [comment]
I am receiving the message as campaign "campaign created successufully" but not able to see the campaigns in "Alchemy" as well as in the website UI. I am not getting where the data of the form is getting stored.

**Comment by ghousetazeem** [comment]
![image](https://github.com/ahmedsemih/CrowdFunding-dApp/assets/74200389/a5cf08e4-bf5e-4580-b990-697675dc2bfa)
See not able to see anything updated in alchemy.

**Comment by ahmedsemih** [comment]
You can't see the campaigns in alchemy. Only the requests and transactions made through the contract are visible in alchemy. campaign data is stored on the ethereum testnet. You can only see the campaigns on the dapp but the data will remain on the chain forever.

**Comment by ghousetazeem** [comment]
Then how to get the data. I want to show the campaigns data in the ui. but not able to access the data, which api use ?

**Comment by ahmedsemih** [comment]
I used the ethers to interact with the smart contract. You can see it if you look at the clients api file.

**Comment by Amaan-Uddin** [comment]
Hi, I don't know but I am not getting the campaings on the homepage after creating the campaing, what can be the issue. How to configure smart contract on different provider

**Comment by ahmedsemih** [comment]
If you did not get an error message, campaigns will appear on home page after the transaction is completed and the block is processed. Unfortunately I haven't tried to use this application on any other provider other than Alchemy, but it is probably necessary to deploy the smart contract with that provider to the ethereum testnet and assign provider and api key to environment variables.

**Comment by ghousetazeem** [comment]
The problem was with the smart contract. It was not being deployed. So I have created a new directory for smart contract and deployed it. Now it works perfectly fine. Thanks for your time and effort.
