### ISSUE TITLE
What to use as Base Url when Hosting the application

### ISSUE THREAD

**Issue by ghousetazeem** [ahmedsemih/CrowdFunding-dApp#2]
I am trying to deploy this application on netlify but I am struggling to keep my base url. I tried keeping it just: "/api" and "/" but its not working. What should I use in place of that to deploy it successfully.

**Comment by ahmedsemih** [comment]
You must add your domain name at the beginning like this: https://crowdfunding-dapp/api

**Comment by ghousetazeem** [comment]
![image](https://github.com/ahmedsemih/CrowdFunding-dApp/assets/74200389/941235cb-324f-4a9c-8949-1e2f81e2f74b)
![image](https://github.com/ahmedsemih/CrowdFunding-dApp/assets/74200389/44fda22d-44d8-4f1a-bb4d-9ffa8906c3dd)
![image](https://github.com/ahmedsemih/CrowdFunding-dApp/assets/74200389/d599729a-872c-40a5-bf51-781960f62851)


I am getting these errors in deployment. 

the way I did that was first I created a project on netlify using github repo and then after getting the domain, I chagned the github code to the actual  code of my application and did everything right, but don't know whats still the problem is?

**Comment by ahmedsemih** [comment]
Unfortunately I don't know how to fix this issue. I have never deployed a nextjs project to netlify.
