### ISSUE TITLE
Hey CrowdFunding-dApp is not working to create Campaign

### ISSUE THREAD

**Issue by omprakash2929** [ahmedsemih/CrowdFunding-dApp#3]
Hey my name is omprakash
recently I copied your project to understand blockchain but here are all the steps to run this project I **created Campaign** successfully, but the Campaign is not showing please check and Help me

**Comment by ahmedsemih** [comment]
Hi Omprakash, I tested it now and i did not see any problem. If you created campaign successfully it may take some time to process to the blockchain. Check the home page or your account page after few minutes.

**Comment by omprakash2929** [comment]
Here I added my screen recording You see now the bug.

https://github.com/ahmedsemih/CrowdFunding-dApp/assets/91268538/540eaafa-81f8-440d-8f2e-3a5b9e73c512

**Comment by ahmedsemih** [comment]
When you are creating a campaign at the 0:53 of the video, at the top of the metamask popup, under localhost, there must be function name and the contract address but on you there are just "sending sepholiaeth" text and a "you are sending 0 eth" warning. I guess there is a problem on your contract. Eth does not send to the contract and the campaign creation function does not work.

**Comment by ahmedsemih** [comment]
This is working.

![Screenshot 2024-01-19 164602](https://github.com/ahmedsemih/CrowdFunding-dApp/assets/102798814/34dd1433-def6-4069-9911-418b58a361f4)

**Comment by omprakash2929** [comment]
Thank you for response 🙂
Please make one video to how to setup the .env file and contract address and other things help me with this

**Comment by omprakash2929** [comment]
Hii ahmedsemih,  i am try many times not working please help me

**Comment by omprakash2929** [comment]
Hey, I found one more bug in the application. It is a user profile address not changed to another account to connect the application here campaigns create but do not show your account section page ???

**Comment by ahmedsemih** [comment]
I fixed this bug. Thank you for informing me.

**Comment by Atharvsanap29** [comment]
Hello Ahmed,

Even i am facing the same issue as Omprakash.
When creating the campaign, everything turns out to be well until the campaign created successfully popup
but i am not able to view any campaigns in the campaign section.

**Comment by Atharvsanap29** [comment]
Hey Omprakash, 

Were you able to solve the campaign visibility issue on the main page ?
If yes, please let me know how to resolve the issue!

**Comment by omprakash2929** [comment]
Hey Atharvsanp29 

When you deploy your smart contract the use  this command " npx hardhat run scripts/deploy.js --network sepolia" 
Right and then use the copy contract address and paste this your .env file NEXT_PUBLIC_CONTRACT_ADDRESS to

**Comment by Atharvsanap29** [comment]
Hey brother,
I am able to view the campaigns now 
Thankyou so much!
