### ISSUE TITLE
Output error!!!

### ISSUE THREAD

**Issue by 201ranjith** [ahmedsemih/CrowdFunding-dApp#4]
I can't run the code it show like,
module not found: can't resolve '../../../smart-contract/artifacts/contracts/crowdfunding.sol/crowdfunding.json'

Can you solve the issue and help me out.

**Comment by ahmedsemih** [comment]
You must deploy the contract. Please run the following command inside the smart-contract folder:

```
npx hardhat run scripts/deploy.js
```

**Comment by 201ranjith** [comment]
I tried and it also shows error. I have a question. In client and smart-contract installed node package after it show's this error.

module not found: can't resolve '../../../smart-contract/artifacts/contracts/crowdfunding.sol/crowdfunding.json'

If something i missed??

**Comment by ahmedsemih** [comment]
Check the getting started section on the readme. If you are getting an error when installing packages for smart contract try --force. You will not get such an error if you do everything completely.

**Comment by 201ranjith** [comment]
npx hardhat run scripts/deploy.js
Error HH8: There's one or more errors in your config file:

  * Invalid account: #0 for network: sepolia - private key too short, expected 32 bytes

**Comment by ahmedsemih** [comment]
Check your environment variables. If you configured them already probably you are not write the right key for account private key. For getting account private key: Open metamask add-on. Go to the account details. Click to show private key button after that do required actions.
