### ISSUE TITLE
Hosting the project on VERCEL

### ISSUE THREAD

**Issue by Atharvsanap29** [ahmedsemih/CrowdFunding-dApp#5]
Hey brother,

First of all thankyou for the amazing project.
Your project is running completely well on localhost. 
I am having too many issues in hosting the project on Vercel.
If possible could you please provide me with steps on how to host it over Vercel or any other hosting platform?

I shall be deeply thankful for your kind consideration and co-operation.

**Comment by ahmedsemih** [comment]
Hi, actually I was never planning to deploy this project, so the file structure is not suitable for deployment. 
- First you need to create a copy of the imported ``` Smart Contract ``` file in ``` EthersContext.jsx ``` and ``` connectBlockchain.js ``` into utils folder and import it from it.
- Then select client as the root directory on configuration section when deploying to vercel. 
- add the environment variables properly. 
- After this step, even if we solve some issues with the first step, you will probably encounter other errors during deployment (I encountered) and the build will not be successful. Unfortunately I have limited time now and this is all I can help you. I hope you can solve the remaining issues.

**Comment by Atharvsanap29** [comment]
Thank you so much for your response.

I will review the process of deploying the project as outlined above. 
I will update you if I make any progress in hosting it.
