### ISSUE TITLE
need help regarding the tech-stack

### ISSUE THREAD

**Issue by Rane-Aditya** [ahmedsemih/CrowdFunding-dApp#6]
Hello Ahmed,
Do you have any reports or ppts for the project ?
If any could you please mail them to me
I require them for my college review

And if possible could you please help me understand the tech-stack for the project (e.g frontend, backend etc)

**Comment by ahmedsemih** [comment]
I just did this project to learn web3. I have no report or ppt. And you can find the tech stack in the readme. 
In this project, there is no classic backend, instead of backend we interact directly with the smart contract with using  Ethersjs.
